### ISSUE TITLE
Arduino IDE: references

### ISSUE THREAD

**Issue by observator-x** [beegee-tokyo/SX126x-Arduino#10]
The Pingpong sample compiles fine but when i try to compile the LoraWan example:

libraries\SX126x-Arduino-1.0.8\mac\LoRaMacHelper.cpp.o:(.literal.lmh_setSubBandChannels+0x4): undefined reference to `ChannelsDefaultMask'

libraries\SX126x-Arduino-1.0.8\mac\LoRaMacHelper.cpp.o:(.literal.lmh_setSubBandChannels+0x8): undefined reference to `ChannelsMask'

libraries\SX126x-Arduino-1.0.8\mac\LoRaMacHelper.cpp.o:(.literal.lmh_setSubBandChannels+0xc): undefined reference to `ChannelsMaskRemaining'

libraries\SX126x-Arduino-1.0.8\mac\region\Region.cpp.o:(.literal.RegionGetPhyParam+0x0): undefined reference to `RegionUS915GetPhyParam'

libraries\SX126x-Arduino-1.0.8\mac\region\Region.cpp.o:(.literal.RegionSetBandTxDone+0x0): undefined reference to `RegionUS915SetBandTxDone'

libraries\SX126x-Arduino-1.0.8\mac\region\Region.cpp.o:(.literal.RegionInitDefaults+0x0): undefined reference to `RegionUS915InitDefaults'

libraries\SX126x-Arduino-1.0.8\mac\region\Region.cpp.o:(.literal.RegionVerify+0x0): undefined reference to `RegionUS915Verify'

libraries\SX126x-Arduino-1.0.8\mac\region\Region.cpp.o:(.literal.RegionApplyCFList+0x0): undefined reference to `RegionUS915ApplyCFList'

libraries\SX126x-Arduino-1.0.8\mac\region\Region.cpp.o:(.literal.RegionChanMaskSet+0x0): undefined reference to `RegionUS915ChanMaskSet'

libraries\SX126x-Arduino-1.0.8\mac\region\Region.cpp.o:(.literal.RegionAdrNext+0x0): undefined reference to `RegionUS915AdrNext'

libraries\SX126x-Arduino-1.0.8\mac\region\Region.cpp.o:(.literal.RegionComputeRxWindowParameters+0x0): undefined reference to `RegionUS915ComputeRxWindowParameters'

libraries\SX126x-Arduino-1.0.8\mac\region\Region.cpp.o:(.literal.RegionRxConfig+0x0): undefined reference to `RegionUS915RxConfig'

libraries\SX126x-Arduino-1.0.8\mac\region\Region.cpp.o:(.literal.RegionTxConfig+0x0): undefined reference to `RegionUS915TxConfig'

libraries\SX126x-Arduino-1.0.8\mac\region\Region.cpp.o:(.literal.RegionLinkAdrReq+0x0): undefined reference to `RegionUS915LinkAdrReq'

libraries\SX126x-Arduino-1.0.8\mac\region\Region.cpp.o:(.literal.RegionRxParamSetupReq+0x0): undefined reference to `RegionUS915RxParamSetupReq'

libraries\SX126x-Arduino-1.0.8\mac\region\Region.cpp.o:(.literal.RegionNewChannelReq+0x0): undefined reference to `RegionUS915NewChannelReq'

libraries\SX126x-Arduino-1.0.8\mac\region\Region.cpp.o:(.literal.RegionTxParamSetupReq+0x0): undefined reference to `RegionUS915TxParamSetupReq'

libraries\SX126x-Arduino-1.0.8\mac\region\Region.cpp.o:(.literal.RegionDlChannelReq+0x0): undefined reference to `RegionUS915DlChannelReq'

libraries\SX126x-Arduino-1.0.8\mac\region\Region.cpp.o:(.literal.RegionAlternateDr+0x0): undefined reference to `RegionUS915AlternateDr'

libraries\SX126x-Arduino-1.0.8\mac\region\Region.cpp.o:(.literal.RegionCalcBackOff+0x0): undefined reference to `RegionUS915CalcBackOff'

libraries\SX126x-Arduino-1.0.8\mac\region\Region.cpp.o:(.literal.RegionNextChannel+0x0): undefined reference to `RegionUS915NextChannel'

libraries\SX126x-Arduino-1.0.8\mac\region\Region.cpp.o:(.literal.RegionSetContinuousWave+0x0): undefined reference to `RegionUS915SetContinuousWave'

libraries\SX126x-Arduino-1.0.8\mac\region\Region.cpp.o:(.literal.RegionApplyDrOffset+0x0): undefined reference to `RegionUS915ApplyDrOffset'

libraries\SX126x-Arduino-1.0.8\mac\region\Region.cpp.o: In function `RegionGetPhyParam':

C:\Users\HP\Documents\Arduino\libraries\SX126x-Arduino-1.0.8\src\mac\region/Region.cpp:1464: undefined reference to `RegionUS915GetPhyParam'

libraries\SX126x-Arduino-1.0.8\mac\region\Region.cpp.o: In function `RegionSetBandTxDone':

C:\Users\HP\Documents\Arduino\libraries\SX126x-Arduino-1.0.8\src\mac\region/Region.cpp:1464: undefined reference to `RegionUS915SetBandTxDone'

libraries\SX126x-Arduino-1.0.8\mac\region\Region.cpp.o: In function `RegionInitDefaults':

C:\Users\HP\Documents\Arduino\libraries\SX126x-Arduino-1.0.8\src\mac\region/Region.cpp:1464: undefined reference to `RegionUS915InitDefaults'

libraries\SX126x-Arduino-1.0.8\mac\region\Region.cpp.o: In function `RegionVerify':

C:\Users\HP\Documents\Arduino\libraries\SX126x-Arduino-1.0.8\src\mac\region/Region.cpp:1464: undefined reference to `RegionUS915Verify'

libraries\SX126x-Arduino-1.0.8\mac\region\Region.cpp.o: In function `RegionApplyCFList':

C:\Users\HP\Documents\Arduino\libraries\SX126x-Arduino-1.0.8\src\mac\region/Region.cpp:1464: undefined reference to `RegionUS915ApplyCFList'

libraries\SX126x-Arduino-1.0.8\mac\region\Region.cpp.o: In function `RegionChanMaskSet':

C:\Users\HP\Documents\Arduino\libraries\SX126x-Arduino-1.0.8\src\mac\region/Region.cpp:1464: undefined reference to `RegionUS915ChanMaskSet'

libraries\SX126x-Arduino-1.0.8\mac\region\Region.cpp.o: In function `RegionAdrNext':

C:\Users\HP\Documents\Arduino\libraries\SX126x-Arduino-1.0.8\src\mac\region/Region.cpp:1464: undefined reference to `RegionUS915AdrNext'

libraries\SX126x-Arduino-1.0.8\mac\region\Region.cpp.o: In function `RegionComputeRxWindowParameters':

C:\Users\HP\Documents\Arduino\libraries\SX126x-Arduino-1.0.8\src\mac\region/Region.cpp:1464: undefined reference to `RegionUS915ComputeRxWindowParameters'

libraries\SX126x-Arduino-1.0.8\mac\region\Region.cpp.o: In function `RegionRxConfig':

C:\Users\HP\Documents\Arduino\libraries\SX126x-Arduino-1.0.8\src\mac\region/Region.cpp:1464: undefined reference to `RegionUS915RxConfig'

libraries\SX126x-Arduino-1.0.8\mac\region\Region.cpp.o: In function `RegionTxConfig':

C:\Users\HP\Documents\Arduino\libraries\SX126x-Arduino-1.0.8\src\mac\region/Region.cpp:1464: undefined reference to `RegionUS915TxConfig'

libraries\SX126x-Arduino-1.0.8\mac\region\Region.cpp.o: In function `RegionLinkAdrReq':

C:\Users\HP\Documents\Arduino\libraries\SX126x-Arduino-1.0.8\src\mac\region/Region.cpp:1464: undefined reference to `RegionUS915LinkAdrReq'

libraries\SX126x-Arduino-1.0.8\mac\region\Region.cpp.o: In function `RegionRxParamSetupReq':

C:\Users\HP\Documents\Arduino\libraries\SX126x-Arduino-1.0.8\src\mac\region/Region.cpp:1464: undefined reference to `RegionUS915RxParamSetupReq'

libraries\SX126x-Arduino-1.0.8\mac\region\Region.cpp.o: In function `RegionNewChannelReq':

C:\Users\HP\Documents\Arduino\libraries\SX126x-Arduino-1.0.8\src\mac\region/Region.cpp:1464: undefined reference to `RegionUS915NewChannelReq'

libraries\SX126x-Arduino-1.0.8\mac\region\Region.cpp.o: In function `RegionTxParamSetupReq':

C:\Users\HP\Documents\Arduino\libraries\SX126x-Arduino-1.0.8\src\mac\region/Region.cpp:1464: undefined reference to `RegionUS915TxParamSetupReq'

libraries\SX126x-Arduino-1.0.8\mac\region\Region.cpp.o: In function `RegionDlChannelReq':

C:\Users\HP\Documents\Arduino\libraries\SX126x-Arduino-1.0.8\src\mac\region/Region.cpp:1464: undefined reference to `RegionUS915DlChannelReq'

libraries\SX126x-Arduino-1.0.8\mac\region\Region.cpp.o: In function `RegionAlternateDr':

C:\Users\HP\Documents\Arduino\libraries\SX126x-Arduino-1.0.8\src\mac\region/Region.cpp:1464: undefined reference to `RegionUS915AlternateDr'

libraries\SX126x-Arduino-1.0.8\mac\region\Region.cpp.o: In function `RegionCalcBackOff':

C:\Users\HP\Documents\Arduino\libraries\SX126x-Arduino-1.0.8\src\mac\region/Region.cpp:1464: undefined reference to `RegionUS915CalcBackOff'

libraries\SX126x-Arduino-1.0.8\mac\region\Region.cpp.o: In function `RegionNextChannel':

C:\Users\HP\Documents\Arduino\libraries\SX126x-Arduino-1.0.8\src\mac\region/Region.cpp:1464: undefined reference to `RegionUS915NextChannel'

libraries\SX126x-Arduino-1.0.8\mac\region\Region.cpp.o: In function `RegionSetContinuousWave':

C:\Users\HP\Documents\Arduino\libraries\SX126x-Arduino-1.0.8\src\mac\region/Region.cpp:1478: undefined reference to `RegionUS915SetContinuousWave'

libraries\SX126x-Arduino-1.0.8\mac\region\Region.cpp.o: In function `RegionApplyDrOffset':

C:\Users\HP\Documents\Arduino\libraries\SX126x-Arduino-1.0.8\src\mac\region/Region.cpp:1499: undefined reference to `RegionUS915ApplyDrOffset'

**Comment by beegee-tokyo** [comment]
Fixed with release of version 1.1.1
