### ISSUE TITLE
SX1262 in RX boosted mode

### ISSUE THREAD

**Issue by gamma2** [beegee-tokyo/SX126x-Arduino#100]
Good morning,
I need to put the sx1262 in rx boosted mode.
Is it correct to call the RadioRxBoosted function?
If yes where is the best place to call the function?
I use the code "examples\LORAWAN-OTAA-esp32-e22\src\main.cpp"

Tank You

**Comment by beegee-tokyo** [comment]
Looking into the LoRaWAN stack, it is using Radio.RX, so if you want to use boosted mode, you have to change the code in the stack itself.

Never tried that.

**Comment by gamma2** [comment]
Tanks you, i will try it
