### ISSUE TITLE
Using CAD with LoRaWAN

### ISSUE THREAD

**Issue by abish7643** [beegee-tokyo/SX126x-Arduino#104]
is it possible to integrate CAD with the LoRaWAN Example?

My device publishes unconfirmed messages only through a single channel by utilizing the lmh_setSingleChannelGateway function. Will the usage of the Radio Instance (SetCadParams/StartCad - Used in P2P Examples) conflict with the LoRaWAN part of the library?

**Comment by beegee-tokyo** [comment]
I guess it will. LoRaWAN MAC stack has it's own "CAD" function called LBT (Listen Before Talk), but it is only enabled in regions that require it (e.g all AS923 regions).
You can still try it.

**Comment by abish7643** [comment]
is LBT (IsChannelFree) implemented in the same way as CAD (SetCadParams/StartCAD).?
A Bit Confused since a RSSI Threshold is used in the LBT Function.

**Comment by beegee-tokyo** [comment]
Correct, LoRaWAN LBT is very different and not using CAD. It is measuring RSSI levels over some time to detect any messages in the air.
As it is automatically activated for certain LoRaWAN regions, I never looked deeper into it.
