### ISSUE TITLE
Arduino IDE PingPong Example 

### ISSUE THREAD

**Issue by matteodallefeste** [beegee-tokyo/SX126x-Arduino#106]
Goodmorning.
I'm using your library for testing Lora devices with esp32.
Compiling the PingPong Example with the current release give me an error:

In file included from C:\Users\xxxx\Documents\Arduino\libraries\SX126x-Arduino\src\mac\LoRaMacHelper.h:26,
                 from C:\Users\xxxx\Documents\Arduino\libraries\SX126x-Arduino\src\mac\LoRaMacHelper.cpp:22:
C:\Users\xxxx\Documents\Arduino\libraries\SX126x-Arduino\src/mac/Commissioning.h:40:2: error: #error "**SX126x-Arduino V2.0 does support all LoRaWAN regions without definition of 'REGION_XXYYY**.\n\nPlease read detailed information how to use it on https://github.com/beegee-tokyo/SX126x-Arduino/blob/master/README_V2.md"
 #error "SX126x-Arduino V2.0 does support all LoRaWAN regions without definition of 'REGION_XXYYY.\n\nPlease read detailed information how to use it on https://github.com/beegee-tokyo/SX126x-Arduino/blob/master/README_V2.md"

But the ping Pong Example it's only a Lora and not LoraWAN.
Am i wrong in something or there's an issue?

Thanks
Matteo

**Comment by beegee-tokyo** [comment]
What version of the SX126x library are you using?
There was a major change between version 1.x.x and 2.x.x 

Make sure you use both the library and example code from V2.x.x

**Comment by matteodallefeste** [comment]
i just downloaded the latest version  [2.0.20] with Arduino IDE.
If i try to compile the example included in the library package called "PingPong" the compiler return me this error: 

*SX126x-Arduino V2.0 does support all LoRaWAN regions without definition of 'REGION_XXYYY*

But this example is not running LoraWan but only Lora
if i comment the Commissioning.h check al line 39-41 the compiler seem to run properly.

may be useful a conditional check for exclude the code of line 39-41 if we are in Lora mode and not in LoraWan mode?

thanks for your time Bernd!

**Comment by matteodallefeste** [comment]
Probably it's the same problem that you reported on NOTE 3 on the file README_V2.md
Downloading the esp32 package i find many devices with the Lora module.
in these modules it's present by default the Region selection.
So in the build process it include automatically the Region info
![immagine](https://github.com/beegee-tokyo/SX126x-Arduino/assets/62309445/e6cedb16-757f-44d4-a4a4-9a0e4c018ad9)

![immagine](https://github.com/beegee-tokyo/SX126x-Arduino/assets/62309445/7385c753-f94b-443e-b2bb-9644db5fca81)

**Comment by beegee-tokyo** [comment]
That is not the problem here. The problem is the BSP for the Heltec Stick. It has LoRaWAN regions definitions that do not work with the SX126x-Arduino library V2.x.x

Install the SX126x-Arduino library V1.3.3 and it should work again (I guess).
Otherwise contact Heltec to update their BSP to support the latest version of my library.

![image](https://github.com/beegee-tokyo/SX126x-Arduino/assets/512690/1e52599e-0cfa-4ee3-88ae-3e8d6aa1b391)

**Comment by matteodallefeste** [comment]
ok thanks Bernd!
Hava a great day

**Comment by matteodallefeste** [comment]
Issue is caused by BSP and not from the library. May be useful a "Note 5" in the ReadmeV2 documentation
