### ISSUE TITLE
Unable to understand.

### ISSUE THREAD

**Issue by ArshaanTech** [beegee-tokyo/SX126x-Arduino#107]
I am a beginner at LoRa and I am trying to connect LoRa sx 1268 (Ra01SH) with arduino uno and nano. 
I couldn't understand the library at all. Is it possible for you to add a API.md like the other LoRa library so it is easier to understand the code?. if you could help me it would be great. You could give me your discord if possible.
Thank you for looking into the issue.

**Comment by beegee-tokyo** [comment]
There are examples and the function calls are explained in the readme file.
