### ISSUE TITLE
Example code does not send packets without timer

### ISSUE THREAD

**Issue by gamma2** [beegee-tokyo/SX126x-Arduino#108]
Good afternoon,
i'm using the example in the "LORAWAN-OTAA-esp32-e22" directory configured for a heltec_wifi_lora_32_V3 card and it works fine. But when I eliminate the timer that manages the periodic sending of packets, the pgm no longer works (it can't send even a single packet without the timer). What function does this timer have (besides scheduling the periodic sending of packets)?
​

**Comment by beegee-tokyo** [comment]
As you can see in the code, the loop() is empty. The timer is the only function that wakes up the device to send data packets. Without the timer, the code does nothing.
