### ISSUE TITLE
Compilation fails with Arduino IDE and Heltec Wireless Stick (V3)

### ISSUE THREAD

**Issue by nona00** [beegee-tokyo/SX126x-Arduino#109]
#error "SX126x-Arduino V2.0 does support all LoRaWAN regions without definition of 'REGION_XXYYY.\n\nPlease read detailed information how to use it on https://github.com/beegee-tokyo/SX126x-Arduino/blob/master/README_V2.md"

is triggered in Commissioning.h because you have to select a region in the Arduino IDE:

![grafik](https://github.com/beegee-tokyo/SX126x-Arduino/assets/3192606/1e012200-623e-4fd2-b2a6-bd9aaeab4f39)

**Comment by beegee-tokyo** [comment]
Talk with Heltec, they setup their BSP for an old version of the SX126x-Arduino library. Or install latest 1.x version of the library.
