### ISSUE TITLE
Arduino IDE 1.8.19 Linux says "SX126x_patch_scan.h: No such file or directory

### ISSUE THREAD

**Issue by ZachreyNM** [beegee-tokyo/SX126x-Arduino#121]
I tried to compile spectrum_analyzer.ino and got

modules/SX126x/patches/SX126x_patch_scan.h: No such file or directory

**Comment by beegee-tokyo** [comment]
There is no such file in this library.
Where is the spectrum_analyzer.ino coming from. It is not an example of this library either.
