### ISSUE TITLE
Transmission and Reception Timeout Issue on ESP32 PICO

### ISSUE THREAD

**Issue by Meo-ux** [beegee-tokyo/SX126x-Arduino#124]
I am currently conducting testing using an ESP32 Pico paired with the Ebyte E22900M30S LoRa module, utilizing basic receiver and transmitter example code for LoRa. The testing environment is facilitated through platformIO. The hardware configuration consists of an integrated PCB specifically designed for this purpose.

![ESP_spec](https://github.com/beegee-tokyo/SX126x-Arduino/assets/73418082/1a36afcb-e7b1-4809-bb37-53a04cf0d28d)

 Recent testing with the  2.0.24 release has revealed a persistent issue where transmission and reception attempts consistently result in timeouts. Notably, both the OnRxTimeout and OnTxTimeout events are being  triggered whenever transmission or reception is requested.

![LoRA_TxRx_timeout](https://github.com/beegee-tokyo/SX126x-Arduino/assets/73418082/07649312-bd0d-4f18-a034-6129171ea173)

Upon reverting to the 2.0.23 release of the library, the code operates as expected with the same hardware setup.

![LoRA_TxRx_Sucess](https://github.com/beegee-tokyo/SX126x-Arduino/assets/73418082/c3c9ead4-4d8e-419c-a400-4e6abf33066b)

Your expertise and assistance in resolving this matter would be greatly appreciated. Thank you for your attention to this concern.

**Comment by beegee-tokyo** [comment]
Stay with the old version, I do not have much time to investigate the problem. It could be linked to the change with the RX?TX timeouts between the two versions.
