### ISSUE TITLE
Print rssi and snr

### ISSUE THREAD

**Issue by luisgcu** [beegee-tokyo/SX126x-Arduino#19]
Hello, 
nice job done in this library. Still learning how all that works. 
I am trying to print rssi and snr using the example  "Sensor-Gateway-Deepsleep/LoRa-Gateway" data is received correctly from node but LoRa-Gateway   rssi and snr =0 ?
PinPongPio example the rssi and snr it is ok.
any idea?

**Comment by beegee-tokyo** [comment]
Not sure if RSSI and SNR are surviving the deep sleep. It might be that the values are overwritten when I re-initialize the LoRa lib after the ESP32 wake-up.

I am quite busy with another project, so I cannot promise when I find time to look into it.
