### ISSUE TITLE
Sx1262 waveshare pins

### ISSUE THREAD

**Issue by it-newbiee** [beegee-tokyo/SX126x-Arduino#29]
Hi, can you help me with the pinout of sx1262 waveshare board and an arduino nano 33 iot  in order for the lorawan example to work ? 
I don't know how to find the busy, nss or reset pins on the sx1262 
Here is the arduino pinout : https://store.arduino.cc/arduino-nano-33-iot
And here are the shields pins : 
![Screenshot_20210320-122624_Chrome](https://user-images.githubusercontent.com/81018335/111867942-862ad680-8977-11eb-9592-3dc872b7818e.jpg)

**Comment by beegee-tokyo** [comment]
The eByte module shown on the image is a E22 900T22S which is using an UART interface to the MCU, not SPI. My library will not work with this module.
