### ISSUE TITLE
Confusion in terminology: Packages vs Packets

### ISSUE THREAD

**Issue by jpmeijers** [beegee-tokyo/SX126x-Arduino#31]
As far as I understand we should be talking about Packets:
https://en.wikipedia.org/wiki/Network_packet

Not Packages:
https://dictionary.cambridge.org/dictionary/english/package

**Comment by beegee-tokyo** [comment]
Please excuse my German flavored English.

But I think that does not influence the functionality of the library.

If you give me a link to the place I use the "wrong" word, I can correct it.

**Comment by beegee-tokyo** [comment]
Fixed with [82903be](https://github.com/beegee-tokyo/SX126x-Arduino/commit/82903beefedb3238e73d001806658221be3140fd)
