### ISSUE TITLE
Bandwidth Selection

### ISSUE THREAD

**Issue by piyushy6** [beegee-tokyo/SX126x-Arduino#33]
Hi, 
#define LORA_BANDWIDTH 0		// [0: 125 kHz, 1: 250 kHz, 2: 500 kHz, 3: Reserved]

How can I select other bandwidths? Like if I want to use 62.5khz. How to use the 3: Reserved parameter here?

https://github.com/beegee-tokyo/SX126x-Arduino/blob/13ab03f04e4773d636579fc636bdfb8133339f44/examples/PingPong/PingPong.ino#L76

**Comment by beegee-tokyo** [comment]
Using other bandwidths is not supported by this library.
