### ISSUE TITLE
E22 900 M22s using segger embedded studio

### ISSUE THREAD

**Issue by Ahsan-Averos** [beegee-tokyo/SX126x-Arduino#39]
Dear Sir,
As you mention that your base library is **_ISP4520_** module based . And you converted into Arduino Library.
Actually Sir I am interfacing nrf52832 with E22900M22s module and using ISP4520 module Library, my lora communication is working fine for both ping_pong and Tx and Rx temperature example. But when I am using Lorawan library on E22900m22s module so its continuously show this message :

_app: Uplink counter : 120
app: Uplink Data rate : DR_0
app: Uplink TX power : 0
app: Uplink frequency: 868500000
app: FDS update success! FileId: 0x3E8 RecKey:0x1
app: FDS update success! FileId: 0x3E8 RecKey:0x2
app: FDS update success! FileId: 0x3E8 RecKey:0x5
app: Data stored on NVM: 224 bytes
app: MCPS-Request: MCPS_UNCONFIRMED, OK_

Although when I am using your Arduino Library for LORAWAN then is working fine but I need to work on Segger Embedded Studio for this, can you please helping me out in this. How I run ISP4520 library with NRF52832 + E22900M22S on segger?
Is this possible to easily convert Arduino library to segger? Any tips? 
Please also let me know what problem do you face when converting ISP4520 library to Sx126x-Arduino Library.
Thanks

**Comment by beegee-tokyo** [comment]
I have no experience with Segger Studio. But as you mention that you work with ISP4520 and need to use Segger Studio, why do you not just use the [Insight SIP 4520 example code](https://github.com/insightsip/ISP4520-examples). It is written for Segger Studio.
