### ISSUE TITLE
MAC and RP version

### ISSUE THREAD

**Issue by jpmeijers** [beegee-tokyo/SX126x-Arduino#40]
On the new TTNv3 console one needs to choose the MAC version as well as the Region Parameters version.

Normally I default to `LoRaWAN version: MAC V1.0.2` and `Regional Parameters version: PHY V1.0.2 REV B`. This seems to work, but knowing the exact version implemented by this library would be better.

**Comment by beegee-tokyo** [comment]
LoRaWAN version: MAC V1.0.2 and Regional Parameters version: PHY V1.0.2 REV B is correct.
