### ISSUE TITLE
Setting Additional Channels

### ISSUE THREAD

**Issue by abish7643** [beegee-tokyo/SX126x-Arduino#47]
I'm from India and I'm actually confused given the fact that there are only 3 channels configured in TTN and saw the same in [docs of this library](https://github.com/beegee-tokyo/SX126x-Arduino/blob/master/CHANNELS.MD).

### **[Q. 1]** I just want to know whether I could explicitly increase the number of channels/configure the frequencies with this library. 

I want to set additional channels (config.json) to the gateway as well, but I couldn't find anything from Things Stack docs. I already tested with handpicked frequencies. Even though the packets were captured by the gateway (can be seen on the dashboard), it never got transferred to Application Nodes. Once I changed the config, the same one mentioned in Things Network's [repository](https://github.com/TheThingsNetwork/gateway-conf/blob/master/IN-global_conf.json), application nodes on the dashboard started to receive the data.

I assume this was due to the frequency mismatch.

### **[Q 2]** Can I set custom channels on Things Stack, which can also be received application nodes as well (So that I can receive the transmitted data)? 

I just need to know whether I could do it, I'm currently running Things Stack locally.

I have been using your library, and it has been working perfectly fine.
Thank You for that.

**Comment by beegee-tokyo** [comment]
Hello @abish7643 

The answer to both questions is very simple.

# _You_ can't change or add frequencies, this is handled by the LoRaWAN server.

LoRaWAN frequencies are assigned by the LoRa Alliance depending on the region. You can find all regions and their assigned frequencies in the [RP2-1.0.3 LoRaWAN® Regional Parameters](https://lora-alliance.org/resource_hub/rp2-1-0-3-lorawan-regional-parameters/). RP2-V1.0.3 is the latest version at this time.

For India 3 frequencies are defined as _**Join**_ frequencies. Nodes can only join the network on these three frequencies.
After successful joining the Network server is using the CFList command to inform the node about five additional frequencies that can be used.
Read more in the chapter 2.12.4  IN865-867 Join-Accept CFList  of above document about it.

Adding these 5 channels in the node is automatically handled by the library. After the node has successfully joined the network, the library gets the CFList from the Network server and adds the five frequencies to the list of usable frequencies. So at the end your node will use 8 channels to transmit data.

**Comment by abish7643** [comment]
Thanks from the reply.

> For India 3 frequencies are defined as Join frequencies. Nodes can only join the network on these three frequencies.
> After successful joining the Network server is using the CFList command to inform the node about five additional frequencies that can be used.

### [Q1] This is applicable only for OTAA mode, right? 

I'm currently using ABP Mode, I'm confused whether the node will receive anything from the gateway if I'm using ABP.
This confusion came from the fact that, the node dynamically adjusts the spreading factor.

### [Q2] Does the nodes receive anything if used in ABP Mode? & The answer you gave above, is it applicable to this as well.

I know I'm asking a bit too much, currently everything is smoky inside my head, trying to make sense out of something.

Thank You Mate.

**Comment by beegee-tokyo** [comment]
@abish7643 
I never tried ABP on regions that use this CFList. I will have to run a test.

**Comment by abish7643** [comment]
I'll try to check that now and update this in the future. 

### [Q1] Do you know how spreading factor changes, does gateway have any role in it?

I'm currently assuming that the gateway is sending something back, which makes the node realize that it need adjust the SF.

**Comment by abish7643** [comment]
@beegee-tokyo

**Comment by abish7643** [comment]
@beegee-tokyo 

### I tried to test with ABP and OTAA, the packets were transmitted at all the frequencies configured in the gateway. So the CFList was probably received by the nodes.

I don't how to debug and make sure that the CFList was received, probably have to deep dive into the source code.
 
I used the frequencies mentioned in TTN's [frequency plans](https://raw.githubusercontent.com/TheThingsNetwork/lorawan-frequency-plans/master/frequency-plans.yml).

> Note: I'm sending packets from 3 nodes, using both ESP32 Pico Kit and ESP32 Dev Kit.
> So Using ESP32 Pico Kit works (Tested Only The LorawanPio Example) without any hassle.

### [Q1] How could I increase the speed of sending the packet from a node. Just want to know how much is the limit and how far I can go?

I have noticed that the delay has been pretty much inconsistent for all the nodes, whatever mode I'm in (ABP and OTAA).

**Comment by beegee-tokyo** [comment]
If you have access to the LoRaWAN gateway, you could look into the log files and see if your node is sending on different frequencies every time and they should be more than the initial 3 join frequencies. I don't know what gateway you are using, but on mine I can see something like this:
![image](https://user-images.githubusercontent.com/512690/131220205-7f6d3c3e-6f3a-4cf3-84c1-c0874ee25eca.png)

Regarding SF, that is not set as a single parameter. Instead in LoRaWAN it is called DR (datarate) and is a combination of  SF and Bandwidth.
There are two options,
- You switch ADR (automatic datarate adjustment) off, then you will send always on the data rate that you setup in the node.
- You switch ADR on, then the LoRaWAN server will try to optimize the data rate, depending on your packet size.

For the frequency you should/could send packets, consider every 1 minute as the fastest, and this is already violating the "fair usage policy" of TTN. Here is the explanation of the policy: https://www.thethingsnetwork.org/forum/t/fair-use-policy-explained/1300

If you want to know how long it takes to transfer your packet, Semtech offers a calculator: https://www.semtech.com/products/wireless-rf/lora-core/sx1261#download-resources Look for **`SX1261 LoRa Calculator`**

Keep in mind, that if you use unconfirmed messages, after you sent a packet, there is a ~6 seconds delay during which the node listens to downlinks from the LoRaWAN server. So you cannot send a new packet before this RX window is finished. The length of the 2 RX windows is different depending on the LoRaWAN server that you use. But for TTN I see a 6 second RX window.

**Comment by abish7643** [comment]
Thank You.
Got way more idea about the LoRaWan.

I'm using Things Stack (Locally) and I'm able to receive all 8 frequencies which I configured in the Gateway Local Instance of Things Stack. And also I verified the same using RTL-SDR & GQRX.

> Keep in mind, that if you use unconfirmed messages, after you sent a packet, there is a ~6 seconds delay during which the node listens to downlinks from the LoRaWAN server. So you cannot send a new packet before this RX window is finished. The length of the 2 RX windows is different depending on the LoRaWAN server that you use. But for TTN I see a 6 second RX window.

Made total sense, but what's `unconfirmed messages`?

**Comment by beegee-tokyo** [comment]
Unconfirmed message => The node does not know if his packet/message was received by the LoRaWAN server.

Confirmed message => LoRaWAN server acknowledges that it received the packet with a short message sent back to the node.

**Comment by abish7643** [comment]
Thanks for all of your input, If there's any sort of testing required in the future I'm willing the help.
