### ISSUE TITLE
Increase SF during join

### ISSUE THREAD

**Issue by battosai30** [beegee-tokyo/SX126x-Arduino#49]
Hi,

I can't find any example/info : in LORAWAN_OTAA_ABP example, after JOINREQ_NBTRIALS the device just stop to try joining. So it tries 3 times in SF7 and just give up. Is there any way to give another shot using SF8, and if it fails, another using SF9 etc ... until SF12 (like in other Lorawan libraries like lmic).

Regards

**Comment by battosai30** [comment]
I dug a lot and found some interesting things : apparently, the increasing SF mecanism already exists.

In LoRaMac.cpp there is LoRaMacMlmeRequest() function, and espacially this lines : 

```
		// Reset variable JoinRequestTrials
		JoinRequestTrials = 0;

		// Setup header information
		macHdr.Value = 0;
		macHdr.Bits.MType = FRAME_TYPE_JOIN_REQ;

		ResetMacParameters();

		altDr.NbTrials = JoinRequestTrials + 1;

		LoRaMacParams.ChannelsDatarate = RegionAlternateDr(LoRaMacRegion, &altDr);
```
And RegionAlternateDr() in EU868 leads to : 

```
int8_t RegionEU868AlternateDr(AlternateDrParams_t *alternateDr)
{
	int8_t datarate = 0;

	if ((alternateDr->NbTrials % 48) == 0)
	{
		datarate = DR_0;
	}
	else if ((alternateDr->NbTrials % 32) == 0)
	{
		datarate = DR_1;
	}
	else if ((alternateDr->NbTrials % 24) == 0)
	{
		datarate = DR_2;
	}
	else if ((alternateDr->NbTrials % 16) == 0)
	{
		datarate = DR_3;
	}
	else if ((alternateDr->NbTrials % 8) == 0)
	{
		datarate = DR_4;
	}
	else
	{
		datarate = DR_5;
	}
	return datarate;
}

```

So theoretically it should switch to the next SF each 8 try. I tested it as it but nothing seems to change (is it possible to know the SF which is used ? For know I check on my operator datas which SF is used and it's always SF7). I forced altDr.NbTrials to a higher and I got the expected SF (48 gives SF12).

 So JoinRequestTrials seems to not be incremented as it should; Any clue ?

**Comment by battosai30** [comment]
Ok now I succesfully get an automatic SF incrementation. I modified RegionEU868AlternateDr() in RegionEU868.cpp to : 

```
int8_t RegionEU868AlternateDr(AlternateDrParams_t *alternateDr)
{
	int8_t datarate = 0;

	if (alternateDr->NbTrials >= 48)
	{
		datarate = DR_0;
	}
	else if (alternateDr->NbTrials >= 32)
	{
		datarate = DR_1;
	}
	else if (alternateDr->NbTrials >= 24) 
	{
		datarate = DR_2;
	}
	else if (alternateDr->NbTrials >= 16)
	{
		datarate = DR_3;
	}
	else if (alternateDr->NbTrials >= 8)
	{
		datarate = DR_4;
	}
	else
	{
		datarate = DR_5;
	}
	return datarate;
}
```
The fact is this function is called each try, using % when JoinRequestTrials is 9 leads to the last else with DR_5, and it only change SF on exact value.

The only cloud in the sky is now, when JoinRequestTrials >=8, my log show a doubled datarate change : 
```
09:54:27.896 -> <LM> Join network failed 21 time(s)
09:54:27.896 -> 
09:54:27.896 -> <LM> altDr.NbTrials = 22
09:54:27.896 -> <LM> LoRaMacParams.ChannelsDatarate = 3
09:54:39.225 -> <LM> altDr.NbTrials = 22
09:54:39.225 -> <LM> LoRaMacParams.ChannelsDatarate = 3
09:54:39.270 -> <LM> JoinRequestTrials = 22
09:54:39.455 -> <LM> OnRadioTxDone
09:54:39.455 -> <LM> OnRadioTxDone => RX Windows #1 4995 #2 5995
09:54:39.455 -> <LM> OnRadioTxDone => TX was Join Request
09:54:44.464 -> <RADIO> RX window timeout = 3000
09:54:48.444 -> <RADIO> RadioIrqProcess => IRQ_RX_TX_TIMEOUT
09:54:48.444 -> <LM> OnRadioRxTimeout
09:54:48.490 -> <LM> Join network failed 22 time(s)
09:54:48.490 -> 
09:54:48.490 -> <LM> altDr.NbTrials = 23
09:54:48.490 -> <LM> LoRaMacParams.ChannelsDatarate = 3
09:54:59.850 -> <LM> altDr.NbTrials = 23
09:54:59.850 -> <LM> LoRaMacParams.ChannelsDatarate = 3
```

**Comment by beegee-tokyo** [comment]
The stuff you are changing here are taken from the original Semtech library V1.0.2. I will not touch that part, it might mess up other things.

**Comment by beegee-tokyo** [comment]
As I said previous, it was V1.0.2.
As this library works quite well and it is a lot of work to make the Semtech stuff Arduino compatible, I did not update for quite some time. 

You are welcome to add improvements and updates, I will check and test and merge if it works.
