### ISSUE TITLE
Stack size for the LORA task 

### ISSUE THREAD

**Issue by robsonos** [beegee-tokyo/SX126x-Arduino#55]
Hi Bernd, I hope you are doing well.

I was wondering if there a reason I am not seeing for stack size of the LORA task to be 4096?:
https://github.com/beegee-tokyo/SX126x-Arduino/blob/910234742bd70b127c49c24ac4a8e0ab6b391e44/src/boards/mcu/board.cpp#L375-L379

From my tests it looks like 200 would be enough for the task to run:
![image](https://user-images.githubusercontent.com/12877584/145660154-d5928051-2db3-42ee-be7d-b4eea41c7a1c.png)

Cheers,
Robson.

**Comment by beegee-tokyo** [comment]
Hi @robsonos 
Yes, I guess it could be set smaller, I didn't really check the requirements. nRF52 and ESP32 have enough RAM.

**Comment by robsonos** [comment]
Are you happy for me to push a PR with those changes?

**Comment by beegee-tokyo** [comment]
This would start a complete re-test of the library for all MCU's and all supported LoRaWAN regions, max and min payloads, and in addition for LoRa P2P.
I cannot do this right now, I simply do not have the time.

**Comment by beegee-tokyo** [comment]
Closed for now.
