### ISSUE TITLE
Odd behavior of ADR on AS923

### ISSUE THREAD

**Issue by yourapiexpert** [beegee-tokyo/SX126x-Arduino#59]
I seem to have come across some odd behavior of ADR on AS923 not present on EU868 (these are the only two I have tested so far).

### ENVIRONMENT

AS923:
- RAK7268 with firmware 1.3.1_RAK b71 w/ gateway config for TTN Australia (AS923)
- WisBlocks API (1.1.11) w/ SX126x-Arduino (2.0.9)
- TTN Community Edition (EU1) w/ device config for TTN Australia (AS923). **DEVICE IS IN CLASS C**
- RAK4631 set to TX_POWER_5, MODE_ADR_ON, REGION 0, LMH_UNCONFIRMED_MSG

EU868:
- RAK2287 w/ 7244C enclosure
- BalenaOS + Basic Station Container
- WisBlocks API (1.1.11) w/ SX126x-Arduino (2.0.9)
- TTN Community Edition (EU1) w/ device config for TTN Australia (EU868). **DEVICE IS IN CLASS C**
- RAK4631 set to TX_POWER_5, MODE_ADR_ON, REGION 5, LMH_UNCONFIRMED_MSG

### OBSERVATIONS

With ADR enabled:

- Looking at the overview page of the RAK7268 I can see that only the two primary channels are being used.  Moreover, when looking at the packet logger I only seem to be receiving one out of every 2 packets in a fairly consistent manner.  Occasionally I will receive a subsequent transmission successfully. Thus at an interval of 5 minutes, every second transmission is almost consistently missed.  The experience and observation are mirrored when sending CLASS C acknowledgments from within the application where such packets are often missed.

With ADR disabled:

- Again based on the overview page of the RAK7268 it can be observed that a full spread of frequencies received via CFList is used and that there are no missing uplink or downlink packets observed.

![adr](https://user-images.githubusercontent.com/25435508/155899959-92b84af4-3242-45ce-9a01-864e6f1002f1.jpg)

On EU868:

Unfortunately, there is no status page, and observations were done purely on the TTN console. Based on observations in either ADR or no ADR modes both uplink and downlink transmissions presented no problems.

Please do let me know what else I can do or what other information I can provide to assist with debug and testing.

-- pogipo

**Comment by beegee-tokyo** [comment]
Hi,
I am never using ADR, I will have to check if there is anything going wrong in the library. The LoRaMAC stack was taken without changes from the Semtech source code, it will take some time to dig through that mess.
I am using AS923-3, which is a variant of the AS923, but the code in the stack is the same for both.
My bigger problem is TTN, as they have no native support for AS923-3, I have to setup the channels manually for every device.

**Comment by beegee-tokyo** [comment]
I run a test:
- I use AS923-3 instead of AS923, but the LoRaMAc stack for both is the same, only difference is a frequency shift of 6.6MHz between the two
- Used RAK7258 (I have only that gateway available) setup for AS923-3, using default channel settings
- Chirpstack LoRaWAN server

I have ADR enabled and DR is 5
![image](https://user-images.githubusercontent.com/512690/155985859-c0bc75df-4083-4546-a6ed-b6a1a0187985.png)

I cannot see any problems and the packets arrive every 1 minute in Chirpstack, 
![image](https://user-images.githubusercontent.com/512690/155985965-51e56de6-12d3-45fd-a3ad-4b2fe6455a89.png)

Then I tested the device against TTN, au1.cloud.thethings.network, and I see the same problem that you have, sporadic a message comes through, but most are lost. Same as you, I can see the messages on the gateway.

Not sure what I can do here, it works fine on LNS like Chirpstack and fails on TTN.

**Comment by yourapiexpert** [comment]
Hi! Thank you so much for the effort and the trouble.

I think you have identified just how messed up TTN is.  I installed a brand new version (3.18) of TTI Stack and AS923 could not be more wrong.  This is the channel map that that RAK268 received against the CFList of the device:

![TTI](https://user-images.githubusercontent.com/25435508/156062920-a285de73-cbfa-4bbf-8553-884fb9672eb4.jpg)

Where the gateway thinks it should be operating...nobody knows. Contrast this to public TTN:

![TTN](https://user-images.githubusercontent.com/25435508/156063046-1cb38d0c-e635-46ed-8a79-b6b4257de793.jpg)

At least the CFList matches the capable frequencies of the gateway.  Just some feedback...I will install a Chirpstack here soon and I already have plans to check on AWS IoT since that is the final destination at the end of the year.

**Comment by beegee-tokyo** [comment]
@yourapiexpert 
No trouble at all. These problems with TTN (specially on everything that is not US915 or EU868) was one of the reasons to use a local Chirpstack LNS or even the built-in LNS of the RAK gateways.

Good luck with your projects.

**Comment by yourapiexpert** [comment]
My sincerest apologies for re-opening this but I think I might have discovered something that might help shed light, or, at least, demonstrates that the problem goes away after days of this.

Even with Chirpstack, I was able to reproduce the missing frames under ADR conditions naturally questioning, re-questioning, and consistently checking the config as it was a brand new install.

However, the penny did not drop until I saw in the logs of the network server what the RAK4631 ('the device') was rejecting NewChannelReq of seemingly valid frequencies.  I almost remember seeing the channel mask for ADR include those rejected frequencies but I am not sure and it seems a big oversight if that's the case so let's just say it's me and my memory.

Everything cleared up, instantly, when I removed this piece of code from src/mac/region/RegionAS923.cpp (line 1065):

```
	        /*
		// We are not allowed to change the frequency
		if (channelAdd->NewChannel->Frequency != Channels[id].Frequency)
		{
			freqInvalid = true;
		}
		*/
```

Suddenly on TTN the problem was no longer prevalent, on Chirpstack no longer prevalent and for the first time I am witnessing a full spread of frequencies sent via CFList + NewChannelReq:

![adr-good](https://user-images.githubusercontent.com/25435508/156262741-dbe86c6d-ef85-45c2-bfb8-8fa5043169b4.jpg)

This helped somewhat with my TTN saga but not fully so I put some extra debug into SX126X and you would not believe what happened:

![TTN_wong_frequency](https://user-images.githubusercontent.com/25435508/156262852-3a630082-5fa8-4b9b-805c-bb31278b3bde.jpg)

For the first few packets everything seems ordinary and you can see that the frequencies line up correctly with what was in the CFList and the only other frequency to come down via NewChannelReq was 922000000.  When ADR kicks in, it all goes pear- shaped and for some or other reason the device starts sending on a frequency not only not advertised via CFList or NewChannelReq but also a frequency not even within the bounds of AS923 which caps off at 923400000 per the TTN global conf file.

_Interestingly if I shift 924600000 down by 1.8MHz then I do come up with a frequency that was advertised in CFList._

![freq_shift](https://user-images.githubusercontent.com/25435508/156266465-e443faf5-89ca-4798-a0b0-174614b434d0.jpg)

Now, to test this theory I did the ugliest and most inelegant hack in radio/sx126x.cpp at around line 440:

```
        // sorry Mr. Blocks for the ugly...
	if (frequency > 923400000)
	{
		frequency -= 1800000;
		LOG_LIB("SX126X", "Frequency adjusted to %luHz", frequency);
	}
```

As you can see, even with ADR enabled I have been able to get an amazing and consistent run with my 30-second intervals on TTN:

![ttn_good](https://user-images.githubusercontent.com/25435508/156266359-2952885d-0edf-413e-a741-58c6db26fdd1.jpg)

I don't know who, what or why these frequencies are shifting.  I would think if it's something TTN is sending then there would be mass outrage from Australia but I just have not so far been able to figure out where this is coming from.  I hope I provided enough information for you to be able to replicate but if not, you know where to find me :)

**Comment by beegee-tokyo** [comment]
That looks strange, I will have to dig in a little bit deeper.
Strange enough, the 1.8MHz shift points to AS923-2 which is -1.8MHz away from the AS923-1 (or default AS923).

The allowed channels 1 to 8 are defined in RegionAS923.h and range from 923.2 to 924.6 MHz, that part comes from the Semtech SX1262 library, I didn't touch that. And these are the channels that the check fails.
![image](https://user-images.githubusercontent.com/512690/156312389-73768947-b7f0-41f7-a5d7-2e939cd52b77.png)

There is one thing I am not 100% sure about. The LoRa Alliance Regional Parameters document states a channel data structure for 16 channels, but the Semtech library channel table has only 8 channels.
![image](https://user-images.githubusercontent.com/512690/156312785-b4369e4a-645a-4e28-9cdc-9dafed812cef.png)

**Comment by yourapiexpert** [comment]
Agreed.  I went down a rabbit hole on that one too but I have some good news.  The entire problem can be cleared up by commenting out the frequency check as well as the following in src/mac/region/RegionAS923.cpp around line 360:

```
oid RegionAS923InitDefaults(InitType_t type)
{
	switch (type)
	{
	case INIT_TYPE_INIT:
	{
		// Channels
		Channels[0] = (ChannelParams_t)AS923_LC1;
		Channels[1] = (ChannelParams_t)AS923_LC2;
		/*
		Channels[2] = (ChannelParams_t)AS923_LC3;
		Channels[3] = (ChannelParams_t)AS923_LC4;
		Channels[4] = (ChannelParams_t)AS923_LC5;
		Channels[5] = (ChannelParams_t)AS923_LC6;
		Channels[6] = (ChannelParams_t)AS923_LC7;
		Channels[7] = (ChannelParams_t)AS923_LC8;
		*/
```

This appears to correctly set channels during the LinkAdrReq.  From an earlier debug here is TTN with the default 7 channels enabled:

```<ADR> Requested channel 0(923200000Hz)
<ADR> Requested channel 1(923400000Hz)
<ADR> Requested channel 2(923600000Hz)
<ADR> Requested channel 3(923800000Hz)
<ADR> Requested channel 4(924000000Hz)
<ADR> Requested channel 5(924200000Hz)
<ADR> Requested channel 6(924400000Hz)
<ADR> Requested channel 7(924600000Hz)
<ADR> Requested channel 8(922200000Hz)
<ADR> Requested channel 9(922400000Hz)
<ADR> Requested channel 10(922600000Hz)
<ADR> Requested channel 11(922800000Hz)
<ADR> Requested channel 12(923000000Hz)
<ADR> Requested channel 13(0Hz)
<ADR> Requested channel 14(0Hz)
<ADR> Requested channel 15(0Hz)
```

Now TTN did not send that many but they got mugged in that list somehow between CFList + NewChanReq and then LinkADRReq.

When I disabled the channels and left only LC1 + LC2:

```
<ADR> Requested channel 0(923200000Hz)
<ADR> Requested channel 1(923400000Hz)
<ADR> Requested channel 2(922200000Hz)
<ADR> Requested channel 3(922400000Hz)
<ADR> Requested channel 4(922600000Hz)
<ADR> Requested channel 5(922800000Hz)
<ADR> Requested channel 6(923000000Hz)
<ADR> Requested channel 7(922000000Hz)
<ADR> Requested channel 8(0Hz)
<ADR> Requested channel 9(0Hz)
<ADR> Requested channel 10(0Hz)
<ADR> Requested channel 11(0Hz)
<ADR> Requested channel 12(0Hz)
<ADR> Requested channel 13(0Hz)
<ADR> Requested channel 14(0Hz)
<ADR> Requested channel 15(0Hz)
```

Not only did the list remain correct, but also:

![perfect_ttn](https://user-images.githubusercontent.com/25435508/156333605-adf75750-1d49-4bdf-97ac-8852eba3b464.jpg)

an absolutely flawless TTN experience.

I don't know what the effort involved is but I see the folks at loramac-node also based theirs on  the reference implementation but have a same yet different AS923 implementation doing something different with the 4 regions.

**Comment by beegee-tokyo** [comment]
@yourapiexpert 
Wow, great finding. I will do some tests.
As I said, the Mac part of the library is more or less taken from Semtech, but it is as well already 2 years old. Could be in there since ever.

Thank you very much for looking into it.

**Comment by beegee-tokyo** [comment]
TTN is stupid.
I setup my device for AS923-3, which is not supported by TTN, you have to set the channel list manually:
![image](https://user-images.githubusercontent.com/512690/156361666-64319723-8969-4602-bce3-ff9500763144.png)

And the CF list I get is still for AS923-1:
![image](https://user-images.githubusercontent.com/512690/156361792-326caa90-32ee-4997-b213-e76668f75a36.png)

My Chirpstack is giving me the correct CF list.
![image](https://user-images.githubusercontent.com/512690/156362073-07ae4ee1-cb43-476a-807d-0d8e73b569fe.png)

Cannot test more against TTN, but I can say for Chirpstack your changes are working.
