### ISSUE TITLE
SX126x FSK mode

### ISSUE THREAD

**Issue by laughingboyjj** [beegee-tokyo/SX126x-Arduino#6]
Hello there!
I am continuing to use your library to do some research and development. When I switch to FSK mode, I find that it is not compatible. Do you have plans to continue to improve it?

**Comment by beegee-tokyo** [comment]
Fixed in last release.
@laughingboyjj thank you for your continuing support to make this library better. You found the bug in the Radio.cpp file which fixed the problem.
