### ISSUE TITLE
RAK4630 AS923 on DEBUG enable join failed not retry

### ISSUE THREAD

**Issue by asupawat** [beegee-tokyo/SX126x-Arduino#66]
Don't known why to make it work on debug enable, the  function RegionAS923TxConfig need to comment this line
//LOG_LIB("AS923", "Using TX Frequency %.1f", Channels[txConfig->Channel].Frequency/1000000.0);

https://github.com/beegee-tokyo/SX126x-Arduino/blob/dc15fab55f3975171959c2255153d14427d989d4/src/mac/region/RegionAS923.cpp#L690

**Comment by beegee-tokyo** [comment]
The library debug output is influencing the timing and can cause problems.
It should be only used when absolute necessary.

Regarding the debug output you are pointing to, I am right now checking something on AS923-3 and it doesn't change whether the module joins or not.
![image](https://user-images.githubusercontent.com/512690/172322179-5db90ea9-db4c-44a6-a508-84368af69c22.png)

**Comment by asupawat** [comment]
I was tested on LORAMAC_REGION_AS923, in normal gateway is online will be fine and successfully joined but if gateway down or without gateway found I can see this problem. This problem not found on v2.0.9

**Comment by beegee-tokyo** [comment]
Changing the line to output the frequency as uin32_t instead of float fixed the problem. 🤔 😕 
Will be in my next release.

Line 690: `LOG_LIB("AS923", "Using TX Frequency %ld", Channels[txConfig->Channel].Frequency);`
