### ISSUE TITLE
use with TTGO T-BEAM

### ISSUE THREAD

**Issue by tomcosk** [beegee-tokyo/SX126x-Arduino#68]
Is it possible to use this lib with ttgo t-beam board? Where can I set DIO, DIO1 and DIO2  ? There is option only for DIO1 in hwConfig.

**Comment by beegee-tokyo** [comment]
Hi @tomcosk 
This library works only with the Semtech SX1262 LoRa transceiver. I couldn't find details, but I think the TTGo T-Beam uses the RAK1272 or RFM95 LoRa transceiver. This library cannot be used with these chips.

**Comment by tomcosk** [comment]
Ah I see, Thank you. I have some ttgo boards here and wanted to use them with this lib. It is much more simpler than lmic. never-mind :-) Thank you.
