### ISSUE TITLE
Allow for different TCXO control voltages

### ISSUE THREAD

**Issue by dberlin** [beegee-tokyo/SX126x-Arduino#82]
Currently the TCXO control voltage is hard coded to 3.3v.

For some boards, like the heltec lora v3 boards, they are using 1.8V

See https://github.com/Heltec-Aaron-Lee/WiFi_Kit_series/blob/master/esp32/libraries/LoraWan102/src/driver/sx126x.c#L79

It would be nice if it was possible to pass along the TCXO control voltage in the setup struct.

**Comment by dberlin** [comment]
#83 implements this

**Comment by beegee-tokyo** [comment]
Nice extension to the functionality.
Thank you for submitting. I will have a quick test this weekend and merge it.
