### ISSUE TITLE
Gatewayzeit

### ISSUE THREAD

**Issue by IGLO70** [beegee-tokyo/SX126x-Arduino#88]
Gibt es die Möglichkeit die UTC Time vom Gateway abzufragen? Grundsätzlich sollte das bei Lora ja mit einem MAC Befehl (lmic_time_reference als Beispiel) möglich sein. Wie funktioniert das mit diesem Library? Bitte um Hilfe.

**Comment by beegee-tokyo** [comment]
You are correct, it is possible to send a time request to the server and receive the time, but this library does not support it.

**Comment by IGLO70** [comment]
Will this be an option in future?

**Comment by beegee-tokyo** [comment]
Sorry for the late reply.
I have no time to implement it at the moment. But as this is open source, you are welcome to contribute a implementation.
